apiVersion: v1
kind: ReplicationController
metadata:
  name: zurmo-webapp-allinone
  labels:
    name: zurmo-webapp-allinone
spec:
  replicas: 2
  selector:
   name: zurmo-webapp-allinone
  template:
    metadata:
      labels:
        name: zurmo-webapp-allinone
    spec:
      containers:
        - name: apache
          image: icclabcna/zurmo_apache:kubernetes
          ports:
          - containerPort: 80
          imagePullPolicy: Always
          env:
          - name: MYSQLHOST
            value: localhost
#        - name: logcourier
#          image: icclabcna/zurmo_log_courier_apache
#        - resources:
#          limits:
#            cpu: 0.5
        - name: mysql
          image: icclabcna/zurmo_mysql
          env:
          - name: MYSQL_ROOT_PASSWORD
          # Change this password!
            value: zurmo
          ports:
          - containerPort: 3306
            name: mysql
          imagePullPolicy: Always
