apiVersion: v1
kind: Pod
metadata:
  name: zurmo-webapp-allinone
  labels:
    name: zurmo-webapp-allinone
spec:
  containers:
        - name: apache
          image: icclabcna/zurmo_apache:kubernetes
          ports:
          - containerPort: 80
          imagePullPolicy: Always
          env:
          - name: MYSQLHOST
            value: localhost
        - name: mysql
          image: icclabcna/zurmo_mysql:kubernetes
          env:
          - name: MYSQL_ROOT_PASSWORD
          # Change this password!
            value: zurmo
          ports:
          - containerPort: 3306
            name: mysql
          imagePullPolicy: Always
