apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: elasticsearch
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: Elasticsearch
  name: elasticsearch
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: db
  selector:
    k8s-app: elasticsearch
  sessionAffinity: None
  type: ClusterIP
