apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kibana
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: Kibana
  name: kibana
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: ui
  selector:
    k8s-app: kibana
  sessionAffinity: None
  type: LoadBalancer
