apiVersion: v1
kind: ReplicationController
metadata:
  generation: 1
  labels:
    k8s-app: kibana
    kubernetes.io/cluster-service: "true"
    version: v1
  name: kibana
spec:
  replicas: 1
  selector:
    k8s-app: kibana
    version: v1
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: kibana
        kubernetes.io/cluster-service: "true"
        version: v1
    spec:
      containers:
      - env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch:9200
        image: gcr.io/google_containers/kibana:1.3
        imagePullPolicy: IfNotPresent
        name: kibana
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
        resources:
          limits:
            cpu: 100m
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
